insert into "events"
("image", "title", "date", "description", "location_id")
values
('https://images.unsplash.com/photo-1645699822985-5b3389ff5b58?q=80&w=1885&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
'borobudur marathon 2024',
'2024-12-01T03:30:00',
'Bank Jateng Borobudur Marathon 2024 kembali hadir! Mengundang seluruh pelari untuk bersama-sama merasakan kemeriahan gelaran Borobudur Marathon. Setiap langkah adalah bagian dari sebuah cerita besar. Selama tujuh tahun, Borobudur Marathon telah menjadi saksi ribuan kisah inspiratif. Warga Magelang dengan bangga menyambut para pelari dalam Borobudur Marathon 2024.', 6),
('https://images.unsplash.com/photo-1541515303410-648f4a06a67a?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
'Pertamina Grand Prix of Indonesia 2024',
'2024-09-27T09:00:00',
'Experience the excitement of the 2024 Pertamina Grand Prix of Indonesia at Mandalika International Circuit. Official Ticket Packages provide premium grandstand seating or MotoGP VIP Village™ hospitality. Enjoy thrilling trackside activities, including Team Garage Experience, Paddock Tours, Rider Meet & Greets, and more in Lombok.', 2),
('https://eventdaerah.kemenparekraf.go.id/storage/app/uploads/public/664/c40/b61/664c40b61c2b4996545661.png',
'Festival Budaya Lembah Baliem',
'2024-08-07T09:00:00',
'Festival Budaya Lembah Baliem ke-32 pada tahun 2024 merupakan ajang atraksi budaya yang bertujuan mempromosikan Wamena sebagai daerah tujuan wisata city branding (ikon promosi daerah) bagi wisatawan nusantara dan mancanegara. Festival ini akan menampilkan jejak peradaban nenek moyang suku Hubula melalui atraksi kolosal perang-perangan, permainan olah raga anak remaja (sikoko dan puradan) yang mengasah ketangkasan melempar tombak, atraksi karapan babi, atraksi Bakar Batu (memasak cara tradisional) serta pergelaran seni tari dan permainan musik tradisional Pikon. Pada puncak acara festival, akan ditampilkan atraksi karnval budaya nusantara sebagai wujud kecintaan terhadap negara dan peringatan Hari Ulang Tahun Kemerdekaan Republik Indonesia ke-79.', 7),
('https://eventdaerah.kemenparekraf.go.id/storage/app/uploads/public/65f/d82/cf6/65fd82cf6b8ed953941908.png',
'Tomohon International Flower Festival',
'2024-08-08T08:00:00',
'Tomohon International Flower Festival (TIFF), sebuah kisah tentang keindahan, keberagaman budaya, warna-warni, harmoni, kebahagiaan dan semangat gotong-royong yang terajut padu mencerminkan keunikan Tomohon sebagai Kota Bunga. Menampilkan rangkaian parade kendaraan hias bunga cantik yang mengundang decak kagum pengunjung.  Dengan keunikan tersebut, asa dan daya seluruh elemen dari kota kecil ini untuk meraih mimpi yang besar. Tahun 2024, TIFF ke-12 mengusung tema "Moving Forward, Getting Stronger" dan akan menjadi landasan pijak masyarakat untuk terus "Bergerak Maju" agar menjadi "Semakin Kuat" dalam kancah persaingan global. TIFF akan menampilkan parade kendaraan hias bunga yang lebih menarik dan spektakuler,dan juga menggelar pameran Floriculture and Investment yang lebih prospektif dan dinamis.', 4),
('https://eventdaerah.kemenparekraf.go.id/storage/app/uploads/public/664/c3d/0dd/664c3d0ddadd1784840895.png',
'Samosir Music Internasional',
'2024-08-09T19:00:00',
'Samosir Music International merupakan event yang menampilkan musisi, baik lokal, nasional, maupun mancanegara dari berbagai genre dengan membawakan musik dan lagu khas Batak. Selain musik, event ini juga mengangkat seni budaya yang berasal dari Provinsi Sumatera Utara serta bazar UMKM dari berbagai produk kuliner maupun produk ekraf lokal. Event ini bukan sekadar perayaan kekayaan musikal semata, tetapi juga merajut hubungan yang kuat antara sektor pariwisata dan ekonomi kreatif. Di tahun penyelenggaraan ketujuh ini, Samosir Music International akan berlangsung selama tiga hari dan akan menampilkan line up musisi berbeda dari tahun sebelumnya. Begitupun partisipasi UMKM yang akan ditingkatkan melalui proses kurasi yang ketat.', 3),
('https://eventdaerah.kemenparekraf.go.id/storage/app/uploads/public/65f/da6/fce/65fda6fce7795681028422.png',
'Festival Pacu Jalur Tradisional',
'2024-08-20T08:00:00',
'Festival Pacu Jalur Tradisional merupakan salah satu event wisata tahunan di Kabupaten Kuantan Singingi yang sudah dilaksanakan lebih dari satu abad. Pacu Jalur adalah salah satu tradisi budaya turun temurun yang diwariskan oleh nenek moyang masyarakat Kuantan Singingi dan merupakan satu-satunya di dunia. Tidak lupa dengan keramaian dan viralitas yang terjadi pada tahun lalu, Pacu Jalur memiliki tukang tari, sosok yang bisa dikatakan sebagai ikon pada masing-masing jalur. Tukang tari biasanya adalah sosok anak kecil yang memiliki keseimbangan tubuh yang bagus, karena pada saat jalurnya menang biasanya tukang tari akan berdiri di haluan jalurnya sambil melakukan selebrasi. Pacu Jalur bukanlah kompetisi semata, tapi juga merupakan salah satu langkah dalam memajukan ekonomi. Dengan tema “Pariwisata Maju, Ekonomi Meningkat, Masyarakat Sejahtera,” Pacu Jalur juga turut dimeriahkan oleh pawai budaya, prosesi begulang dan peragu begandung, festival budaya, pentas seni, festival musik dan kesenian tradisional, serta bazar dan pameran UMKM.', 1),
('https://eventdaerah.kemenparekraf.go.id/storage/app/uploads/public/664/be3/64b/664be364b2d48131443061.png',
'Musik Alam Fest',
'2024-09-27T19:00:00',
'Musik Alam Fest adalah sebuah event yang berangkat dari semangat kalangan muda dan komunitas untuk melestarikan kebudayaan lokal Kalimantan Utara melalui musik, tari-tarian, dan pertunjukan seni budaya lainnya. Event ini dilaksanakan untuk merangsang minat masyarakat, khususnya kalangan muda untuk turut serta membangun kepedulian antar sesama dan melestarikan kearifan budaya lokal di Kalimantan Utara. Selain itu, Musik Alam Fest juga bertujuan untuk menciptakan ruang bagi para pelaku UMKM untuk memasarkan produk lokal mereka dan secara tidak langsung dapat meningkatkan perekonomian dan membangun basis pemasaran untuk produk UMKM.', 6),
('https://eventdaerah.kemenparekraf.go.id/storage/app/uploads/public/664/b62/e35/664b62e35d10c809346979.png',
'Jakarta Dessert Week',
'2024-09-30T09:00:00',
'Jakarta Dessert Week (JDW) merupakan rangkaian kolektif kegiatan dessert tahunan yang berkomitmen untuk meningkatkan kesadaran akan perkembangan industri makanan manis. JDW merupakan acara pertama yang memperkenalkan konsep restaurant-week di Indonesia, memberikan pengalaman unik bagi para pecinta makanan manis untuk menjelajahi berbagai hidangan lezat dari para ahli di bidangnya. Sebagai sebuah festival yang merayakan kekayaan dan keragaman dessert, JDW juga menjadi platform kreatif bagi para chef, pelaku industri, dan penggemar kuliner untuk berkumpul, berbagi, dan menikmati kreasi terbaik dari industri dessert di Jakarta.', 2),
('https://eventdaerah.kemenparekraf.go.id/storage/app/uploads/public/664/b3b/342/664b3b342d730842313501.png',
'Wayang Jogja Night Carnival',
'2024-10-07T20:00:00',
'WJNC merupakan karnaval jalanan (art on the street) dengan menggabungkan tema pewayangan yang telah dilaksanakan secara rutin sejak tahun 2016.  Penampilan karnaval ini melibatkan seni koreografi, busana, musik kontemporer, dan permainan lighting. Pada perkembangannya, konsep karnaval berubah menjadi street art dengan tidak meninggalkan unsur utama dari WJNC, yaitu Tugu Jogja, kendaraan hias, Wayang dan diadakan pada malam hari. WJNC menyuguhkan karnaval dengan konsep street art dan membawakan tema-tema dari cerita pewayangan yang melibatkan peserta dari 14 Kemantren (kecamatan) di Kota Yogyakarta.', 7),
('https://eventdaerah.kemenparekraf.go.id/storage/app/uploads/public/65f/e78/2cd/65fe782cd4f98155391047.png',
'Indonesian Contemporary Art & Design',
'2024-10-10T09:00:00',
'Indonesian Contemporary Art & Design (ICAD) menjembatani seni dan desain mulai dari desain interior, desain produk, arsitektur, komunikasi visual, dengan disiplin ilmu lainnya mulai dari fashion, film, perhotelan, teknologi, makanan dan minuman, dan banyak lagi. ICAD merupakan platform pertama dan satu-satunya yang memfasilitasi kolaborasi antara berbagai disiplin ilmu tersebut dan menjadi pameran berskala besar yang mempromosikan desain dan seni kontemporer di Indonesia, serta merangkul keragaman ekspresi budaya bangsa.', 3);